# Generated by Django 5.2.5 on 2026-02-28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата урока')),
                (
                    'lesson_type',
                    models.CharField(
                        choices=[
                            ('group', 'Групповой'),
                            ('individual', 'Индивидуальный'),
                            ('masterclass', 'Мастер-класс'),
                            ('makeup', 'Отработка'),
                        ],
                        max_length=20,
                        verbose_name='Тип урока',
                    ),
                ),
                (
                    'lesson_format',
                    models.CharField(
                        choices=[('online', 'Онлайн'), ('offline', 'Оффлайн')],
                        max_length=10,
                        verbose_name='Формат урока',
                    ),
                ),
                (
                    'students_count',
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='Обязательно для групповых уроков',
                        null=True,
                        verbose_name='Количество детей',
                    ),
                ),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
